-- MySQL Script generated by MySQL Workbench
-- 09/08/16 10:53:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mlg_mbo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mlg_mbo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mlg_mbo` DEFAULT CHARACTER SET utf8 ;
USE `mlg_mbo` ;

-- -----------------------------------------------------
-- Table `mlg_mbo`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mlg_mbo`.`user` ;

CREATE TABLE IF NOT EXISTS `mlg_mbo`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `score` DECIMAL(11,2) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mlg_mbo`.`question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mlg_mbo`.`question` ;

CREATE TABLE IF NOT EXISTS `mlg_mbo`.`question` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `question` TEXT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mlg_mbo`.`user_has_question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mlg_mbo`.`user_has_question` ;

CREATE TABLE IF NOT EXISTS `mlg_mbo`.`user_has_question` (
  `user_id` INT NOT NULL,
  `question_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`, `question_id`),
  INDEX `fk_user_has_question_question1_idx` (`question_id` ASC),
  INDEX `fk_user_has_question_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_has_question_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `mlg_mbo`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_question_question1`
    FOREIGN KEY (`question_id`)
    REFERENCES `mlg_mbo`.`question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
